version: '3.8'

services:
  backend:
    image: django-advance-blog:latest
    container_name: django_blog_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py prepare_app && gunicorn DjangoAdvanceBlog.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: django_blog_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: django_blog_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  db_data: