# Generated by Django 4.2.15 on 2025-05-26 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_score_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profile",
            name="score",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
