# Generated by Django 4.2.15 on 2025-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_image_throttlerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="throttlerecord",
            name="last_blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
